from enum import Enum

class CaseState(str, Enum):
    DRAFT = 'DRAFT'
    PUBLISHED = 'PUBLISHED'
    VERIFICATION = 'VERIFICATION'
    VOTING = 'VOTING'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'
    PAYMENT_DONE = 'PAYMENT_DONE'
    DOCUMENTS_RECEIVED = 'DOCUMENTS_RECEIVED'
    CLOSE = 'CLOSE'
